### ISSUE TITLE
Type constraint on V in treemap is unnecessary

### ISSUE THREAD

**Issue by YoungerLee** [ugurcsen/gods-generic#7]
The type constraint on parameter V in treemap is not necessary, otherwise the any value is not allowed. What I need is
```
var t treemap.Map[string, any] = treemap.NewWithStringComparator[any]()
```
but the type parameter V is limited by **comparable**.
```
// Map holds the elements in a red-black tree
type Map[K, T comparable] struct {
	tree *rbt.Tree[K, T]
}
```
Consider the following code?
```
type Map[K comparable, T any] struct {
	tree *rbt.Tree[K, T]
}
```

**Comment by ugurcsen** [comment]
I have to decrease code duplication first after that I will fix this.

**Comment by ugurcsen** [comment]
Can you create a pr for this issue?

**Comment by YoungerLee** [comment]
> Can you create a pr for this issue?

ok
